### ISSUE TITLE
Naming conflicts with PUN 2

### ISSUE THREAD

**Issue by Seneral** [rwth-acis/VIAProMa#128]
The current version seems to have naming conflicts with Photon and MRTK.

One conflicting change is [SerializedObject](https://github.com/rwth-acis/VIAProMa/blob/master/Frontend/VIAProMa/Assets/Scripts/SaveLoadSystem/Core/SerializedObject.cs) in public namespace , which conflicts with [UnityEditor.SerializedObject](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/SerializedObject.html), error in Photon
Two more are Axis and File

Attached is a file of the unity editor log
[Editor.log](https://github.com/rwth-acis/VIAProMa/files/5754765/Editor.log)

**Comment by BenediktHensen** [comment]
It seems that an update to PUN2 now accesses classes with this name. We have included the VIAProMa classes in their own namespace, so now the naming conflict should be resolved.
