### ISSUE TITLE
Photon Voice error when setting up the project from scratch

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/VIAProMa#235]
**Describe the bug**
When setting up the project according to the instructions in the readme, there is a compiler error left in the console:

```Assets\Scripts\Multiplayer\VoiceRecorderManager.cs(16,62): error CS1503: Argument 1: cannot convert from 'Photon.Voice.VoiceClient' to 'Photon.Voice.Unity.VoiceConnection'```

**To Reproduce**
1. Freshly clone the project
2. Set it up according to the instructions in the readme
3. Specifically, download the Photon PUN and Photon Voice libraries from the Asset Store
4. Check the console for errors

**Expected behavior**
No compiler errors should appear.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29382867/124250203-ec052d80-db24-11eb-90bd-298db664f2ef.png)

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [X] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [ ] Smartphone
- [ ] Other: 

**Additional context**
It seems like the API of the Photon Voice library has changed recently.

**Comment by EmilieHK** [comment]
Although I was unable to recreate the error on the master branch, I made a change to the VoiceRecorderManager script that should solve the issue. The same error occured on another branch and was fixed with the same change. Hence, the error should be resolved on the master branch as well, however, I would kindly recommend to verify it.

**Comment by BenediktHensen** [comment]
Ok, I pushed the develop version to master and also updated my local Photon library. The error seems to be gone. Well done!
