### ISSUE TITLE
"Bounding Box" is deprecated

### ISSUE THREAD

**Issue by KritiaSthovania** [rwth-acis/VIAProMa#241]
The "Bounding Box" component from MRTK used by "App Bar" is deprecated. It should be migrated to the new "Bounds Control" component.

**Comment by SebastianMeinberger** [comment]
Currently stale, because in order to use the new Bounds Control, the App Bars needs the GetRawBBCorners Method, which currently is unavailable until the fix for this issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10083 is released with a new MRTK release.

**Comment by SebastianMeinberger** [comment]
The needed MRTK fix will be included in the 2.7.3 release
