### ISSUE TITLE
Closing the issue shelf while logged in leaves edit buttons behind

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/VIAProMa#270]
**Describe the bug**
If I close the shelf and the edit buttons were visible, they are left behind.

**To Reproduce**
1. Open the issue shelf
2. Log in
3. Open a project to display lots of task cards in the shelf
4. Close the shelf using the X button

**Expected behavior**
The buttons should also be hidden like the rest of the shelf

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29382867/126377137-c1843923-1b28-464e-9c35-5466a5aff9e4.png)

**Bug Observed on the Following Devices**
- Unity editor

**Comment by BenediktHensen** [comment]
might be related to #271

**Comment by EmilieHK** [comment]
This has been resolved on the develop branch by attaching the buttons as child-objects to the List View Item. They should now follow every move and be invisible when the shelf is closed.
