### ISSUE TITLE
Moving the issue shelf while logged in sometimes causes edit buttons to detach

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/VIAProMa#271]
**Describe the bug**
If the user is logged in and displays some task cards in the issue shelf, the corresponding editor buttons sometimes detach when moving the shelf. I think this happens if you move the shelf rapidly. It is also possible to re-attach the buttons by bringing the shelf close to the position where the buttons were lost.

**To Reproduce**
1. Open the issue shelf
2. Log in
3. Display a project with lots of task cards
4. Click the bounding box button on the issue shelf to enable the movement mode
5. Move the shelf around fairly quickly

**Expected behavior**
The buttons should follow the shelf and not get detached.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29382867/126377784-9d6dfe9f-e022-4c1f-9063-017a98e788de.png)

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- Unity editor

**Comment by EmilieHK** [comment]
See #270
