### ISSUE TITLE
Editing Buttons also cause issue card copy to spawn

### ISSUE THREAD

**Issue by EmilieHK** [rwth-acis/VIAProMa#272]
**Describe the bug**
If the user is logged in and displays some task cards in the issue shelf, clicking the corresponding editor buttons will result in the respective action being taken and a new Issue in Scene instance of the issue is created at the spot.
**To Reproduce**
1. Open the issue shelf
2. Log in
3. Display a project with lots of task cards
4. Click one of the editing buttons

**Expected behavior**
The editing button action should be taken and no issue card should be spawned.

**Screenshots**
![bug](https://user-images.githubusercontent.com/44223481/126515067-a4458b5f-5895-423b-be15-ff6fe32278ba.PNG)

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- Unity editor

**Comment by JulianStaab** [comment]
Fixed by changing the parent of the buttons to the IssueShelf itself and updating the positions every update.
