### ISSUE TITLE
RequirementsBazaar Issue Creation Problem

### ISSUE THREAD

**Issue by JulianStaab** [rwth-acis/VIAProMa#457]
**Describe the bug**
One can no longer create new Requirements in ViaProMa due to a REST error that requires a password when an OIDC access token is sent.

**To Reproduce**
1. Create a Room.
2. Click on Issue Shelf.
3. Press the Login Button on the Issue Shelf Configuration Menu.
4. Select a Project.
5. Press the Add Requirement Button in the Issue Shelf.
6. Enter a Title and Description and press Post Issue.

**Expected behavior**
A new issue card should be created and uploaded to RequirementsBazaar.

**Screenshots**
![error](https://user-images.githubusercontent.com/19326682/175557736-799a408a-1c10-4a0e-8f5a-e6c1a0dc006f.png)

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [x] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [ ] Smartphone
- [ ] Other:

**Comment by fxjordan** [comment]
The authorization flow in Requirements Bazaar (and actually all other las2peer services) is not the same as in usual API services supporting OIDC. My predecessor has created an issue for this some time ago, https://github.com/rwth-acis/las2peer/issues/96.

You always have to set **both headers**: The OIDC access token needs to be in the `access-token` header. And the `Authorization` headers needs to be a `Basic` authentication header with the `preferred_username` as username and `sub` as password, where *sub* and *preferred_username* are the values from the JWT encoded access token.

The Requirements Bazaar frontend sets the headers for authenticated requests as follows:

https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/blob/8af8922b9ab3d1d2fe8152f246c6a621f6d024e4/src/api/bazaar.ts#L4-L19
