### ISSUE TITLE
Drag-and-Drop Issues can sometimes not be moved after letting go of them

### ISSUE THREAD

**Issue by ossocore** [rwth-acis/VIAProMa#465]
**Describe the bug**
Sometimes Issues can not be moved after letting go of them while they are colliding with a visualization, moving another issue and then trying to move the bugged issue again has been proven to work, but also not reliably.

**To Reproduce**
1. Go to the DnD testscene
2. enter play mode and drag an issue (onto a visualization for example)
3. let go of it, then try to move it again (doesn't happen all the time)

**Expected behavior**
always beeing able to immediately move the issue again after letting go of it

**Comment by PaulMWeiser** [comment]
This can also happen if the drag-and-drop component is deactivated, so it seems to be a problem with the whole program.
It is also easy to reverse, i.e. by rotating the component a bit or restarting the manipulation component
