### ISSUE TITLE
Delete Issue Button on Kanban Board

### ISSUE THREAD

**Issue by JulianStaab** [rwth-acis/VIAProMa#496]
**Describe the bug**
The Delete Issue button from the Issue Shelf also appears on the Kanban Board Visualization if Issues from the RequirementsBazaar are selected.

**To Reproduce**
1. Start VIAProMa
2. Open a room
3. Open the Issue and Visualization shelfs
4. Load some issues from the Requirements Bazaar
5. Select the Kanban board from the shelf and drag it into the scene
6. Select some issues in the Kanban board settings
7. Click on the down button on the Kanban board and then up again
8. The delete button will appear

**Expected behavior**
The Delete Issue button should never appear in the Kanban Board Visualization.

**Screenshots**
![C59568E3-05EB-4683-8D4A-4FCCB06A56A9](https://user-images.githubusercontent.com/19326682/181206543-45ac1efe-a757-42a4-b53c-609f876000e2.jpeg)
![2FF9E6B4-EB44-4AAB-BAB1-AB3AB4D0C4DE](https://user-images.githubusercontent.com/19326682/181206550-f27c8f01-bbd7-40eb-bbb6-964caec51fca.jpeg)

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [x] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [ ] Smartphone
- [ ] Other:

**Comment by EmilieHK** [comment]
Resolved and part of the Pull-Request #498. The Delete and Edit Button of Issue Cards are disabled when the Issue Shelf is not detected as a parent of it.
