### ISSUE TITLE
Huge Background object on Competence Display

### ISSUE THREAD

**Issue by JulianStaab** [rwth-acis/VIAProMa#497]
**Describe the bug**
When using the competence display, after assigning some issues to it, a dark background object with huge dimensions will appear and cover almost half of the screen.

**To Reproduce**
1. Start VIAProMa
2. Open a room
3. Open the Issue and Visualization shelfs
4. Load some issues from the Requirements Bazaar
5. Select the Competence display from the shelf and drag it into the scene
6. Select some issues in the competence display settings
8. The huge background object will appear

**Expected behavior**
This background object should not appear at all.

**Screenshots**
![64749DB6-7796-4491-9B73-052D6B71BC7F](https://user-images.githubusercontent.com/19326682/181207347-67552b39-911a-4c02-b9e0-e0f0a0da5527.jpeg)

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [x] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [ ] Smartphone
- [ ] Other:

**Comment by EmilieHK** [comment]
This error occurred for text label objects with the corresponding text being only a whitespace, resulting in a faulty mesh update by `TextMeshPro`. The whitespace is the result of concatenating the first and last name of a user in cases where these were both empty in `UserScoreDisplay.cs`. The problem has been solved by instead setting the text of a label to the user name in those cases. The solution is contained in the pull-request #498.
