### ISSUE TITLE
Delete Specific Lines

### ISSUE THREAD

**Issue by EmilieHK** [rwth-acis/VIAProMa#8]
In addition to deleting all lines, specific lines should be selected and deleted. For this, an additional button should be added. When it is clicked it turns to the color red (this is an example, it should be possible to distinguish the states of the button), the user is able to select a specific line and with another click on the same button (caption saying "Delete Line") the corresponding gameobject containing the LineRenderer is destroyed.

**Comment by Mareska** [comment]
When Button is clicked is should turn red. Afterward when moving the courser with click pressed down on the line the line should turn red, if the click is released the line is destroyed and the Button turns back in its original color.
