### ISSUE TITLE
Avoid lines with the same end points

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/VIAProMa#82]
**Description**
Lines can have the same start and end point which produces an empty LineRenderer object in the scene.

**Steps to Reproduce**
1. Create a room
2. Open the issue shelf, select a project and drag an issue card into the scene.
3. Open the connection lines menu, click "Enter Line Draw".
4. Tap on the issue card to select it. Tap on the same issue card again.
5. Click the "Draw Line" button.
6. Inspect the scene's object hierarchy. A new "LineRenderer (Clone)" object was created.

**Expected Behavior**
If only one object was selected, no line should be created.

**Comment by EmilieHK** [comment]
An object can now only be selected once, preventing the lines with the same end and start point. This solution has the effect that an object can be deselected by selecting another third object as the new choice but not by clicking the object twice as this causes a problem with ambiguity in the selection mode.
