### ISSUE TITLE
Gaze Cursor in HoloLens mode does not use normal vector of object anymore

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/VIAProMa#86]
**Description**
The gaze cursor is pointing into the wrong direction on some of the objects. This seems to happen only in HoloLens mode where the pointer follows the gaze cursor.

**Steps to Reproduce**
1. Create a room
2. Create any object in the room, e.g. an issue card
3. Look at the issue card.

**Expected Behavior**
The pointer should adapt to the surface's normal and rotate accordingly.

**Attachments**
![Example](https://user-images.githubusercontent.com/29382867/84888368-7a804b80-b097-11ea-85cc-a8a5a99dc79d.png)

**Comment by danielbekhter** [comment]
I could not replicate this issue. Which branch does it occur on? What is the hand simulation input setting? Is InputSourceType in the script InstantiateArrows set to Controller or Hand? 

I am on NewMainBranch.

Here is my test with the Gestures hand simulation mode and the Controller input source type: <img width="656" alt="image" src="https://user-images.githubusercontent.com/57594319/85275338-7c278600-b480-11ea-8e31-9c770a676dac.png">

Here is my test with the Gestures hand simulation mode and the Hand input source type: 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/57594319/85275958-5d75bf00-b481-11ea-9717-f87b9256ea5c.png">

**Comment by danielbekhter** [comment]
Issue cards with Gestures hand simulation mode and the Hand input source type: 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/57594319/85277906-7b90ee80-b484-11ea-876b-7d7f58207e7a.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/57594319/85277975-906d8200-b484-11ea-817f-9af0d939cbed.png">

**Comment by danielbekhter** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/57594319/85278115-c90d5b80-b484-11ea-8257-88454415859b.png">
